const suggestions = {
  '01d': 'Ricordati la crema solare!',
  '01n': 'Buonanotte!',
  '02d': 'Oggi il sole va e viene...',
  '02n': 'Attenti ai lupi mannari...',
  '03d': 'Luce perfetta per fare foto!',
  '03n': 'Dormi sereno :)',
  '04d': 'Che cielo grigio :(',
  '04n': 'Non si vede nemmeno la luna!',
  '09d': 'Prendi l\'ombrello',
  '09n': 'Copriti bene!',
  '10d': 'Prendi l\'ombrello',
  '10n': 'Copriti bene!',
  '11d': 'Attento ai fulmini!',
  '11n': 'I lampi accendono la notte!',
  '13d': 'Esci a fare un pupazzo di neve!',
  '13n': 'Notte perfetta per stare sotto il piumone!',
  '50d': 'Accendi i fendinebbia!',
  '50n': 'Guida con prudenza!'
};
